apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: simplog-snap
spec:
  snapshotClassName: csi-xtremio-xvc
  source:
    name: simplog-csi
    kind: PersistentVolumeClaim
