apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplog-snap-restore
spec:
  storageClassName: csi-xtremio-sc
  dataSource:
    name: simplog-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
